export const MENU = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: '/icons/ic_home.svg',
    icon_active: '/icons/ic_home_active.svg',
    url: '/',
  },
  {
    id: 'transactions',
    label: 'Transactions',
    icon: '/icons/ic_transfer.svg',
    icon_active: '/icons/ic_transfer_active.svg',
    url: '/transactions',
  },
  {
    id: 'accounts',
    label: 'Accounts',
    icon: '/icons/ic_account.svg',
    icon_active: '/icons/ic_account_active.svg',
    url: '/accounts',
  },
  {
    id: 'investments',
    label: 'Investments',
    icon: '/icons/ic_economic_investment.svg',
    icon_active: '/icons/ic_economic_investment_active.svg',
    url: '/investments',
  },
  {
    id: 'credit_cards',
    label: 'Credit Cards',
    icon: '/icons/ic_credit_card.svg',
    icon_active: '/icons/ic_credit_card_active.svg',
    url: '/credit-cards',
  },
  {
    id: 'loans',
    label: 'Loans',
    icon: '/icons/ic_loans.svg',
    icon_active: '/icons/ic_loans_active.svg',
    url: '/loans',
  },
  {
    id: 'services',
    label: 'Services',
    icon: '/icons/ic_service.svg',
    icon_active: '/icons/ic_service_active.svg',
    url: '/services',
  },
  {
    id: 'my_privileges',
    label: 'My privileges',
    icon: '/icons/ic_privileges.svg',
    icon_active: '/icons/ic_privileges.svg',
    url: '/my-privileges',
  },
  {
    id: 'setting',
    label: 'Setting',
    icon: '/icons/ic_settings_solid.svg',
    icon_active: '/icons/ic_settings_solid_active.svg',
    url: '/setting',
  },
]
